theme: jekyll-theme-minimal
title: Applied Quantitative Methods for the Social Sciences II
production_url: https://franvillamil.github.io/advanced_quant
BASE_PATH: https://franvillamil.github.io/advanced_quant
